rename NFeAccessKey to SpedAccessKey
brazanation/documents pull request #24
Opened 2016-10-17 19:19 UTC by tonicospinelli

fix #23

2016-10-17 19:24 UTC, robmachado requested changes
@tonicospinelli 

Vode deve lembrar que fazendo essa alteração o MODELO do documento deve ser passado no método generate 
Os modelos podem ser 55, 65, 57, etc

2016-10-17 19:32 UTC, robmachado commented
Eu estava esquecendo de um parâmetro 

$tpEmis = tipo de emissão não é fixo tem que ser passado pois muda com as contingências

2016-10-17 19:35 UTC, tonicospinelli commented
@robmachado sabe me informar algum lugar onde eu consigo pegar essa lista de modelo completa?

2016-10-17 19:43 UTC, robmachado commented
Segue:

NFe = 55 (nota normal)
NFCe = 65 (nota consumidor)
CTe Cargas 57 (conhecimento para cargas)
CTe Outros 67 (conhecimento para outros transportes)
MDFe 58 (manifesto de transportes)
Isso que você queria ?

2016-10-17 19:49 UTC, robmachado commented
Já o tipo de emissão pode ser para NFe:
1 = Emissão normal (não em contingência);
2 = Contingência FS-IA, com impressão do DANFE em formulário de segurança;
3 = Contingência SCAN (Sistema de Contingência do Ambiente Nacional);
4 = Contingência DPEC (Declaração Prévia da Emissão em Contingência);
5 = Contingência FS-DA, com impressão do DANFE em formulário de segurança;
6 = Contingência SVC-AN (SEFAZ Virtual de Contingência do AN);
7 = Contingência SVC-RS (SEFAZ Virtual de Contingência do RS);
9 = Contingência off-line da NFC-e

Para CTe:
1 = Normal;
4 = EPEC pela SVC;
5  = Contingência FSDA;
7 =  Autorização pela SVC-RS;
8 = Autorização pela SVC-SP

Para MDFe:
1 = Normal
2 = Contingência

2016-11-04 14:01 UTC, robmachado commented
@tonicospinelli E ai parceiro, avançou com algo ?

2016-11-28 11:13 UTC, tonicospinelli commented
@robmachado hoje estou retomando isso aqui!! agora vai!! 😄

2016-11-28 11:29 UTC, robmachado commented
Uebaaa! o cara tá vivo !!!

2016-11-28 16:34 UTC, tonicospinelli commented
@robmachado ficou assim:

```php
use Brazanation\Documents\Sped\NFe;
use Brazanation\Documents\Exception\InvalidDocument as  InvalidDocumentException;

try {
    $accessKey = new NFe('52060433009911002506550120000007800267301615');
    echo $accessKey; // prints 52060433009911002506550120000007800267301615
    echo $accessKey->format(); // prints 5206 0433 0099 1100 2506 5501 2000 0007 8002 6730 1615
catch (InvalidDocumentException $e){
    echo $e->getMessage();
}
```

2016-11-28 17:16 UTC, robmachado commented
Opa! para mim parece correto ... faça o pull request que eu faço mais testes e incluo nos projetos :+1:

2016-11-28 17:53 UTC, merged