[ADD] Validação dos números de processos judiciais
brazanation/documents pull request #38
Opened 2018-08-03 18:49 UTC by robmachado

2018-08-08 03:27 UTC, tonicospinelli requested changes
faltou adicionar o exemplo também no README

2018-08-08 03:27 UTC, tonicospinelli commented on src/JudiciaryProcess.php
> +        //remove DD and add double zeros at the end
esse comentário não é necessário, você pode adicionar um docblock e descrever melhor o que acontece dentro do método

2018-08-08 03:27 UTC, tonicospinelli commented on src/JudiciaryProcess.php
> +final class JudiciaryProcess extends AbstractDocument
😍

2018-08-08 03:27 UTC, tonicospinelli commented on src/JudiciaryProcess.php
> +        return preg_replace(self::REGEX, '$1-$2.$3.$4.$5.$6', "{$this}");
neste caso, sugiro não modificar o valor da propriedade `number` ela não deve ser modificada em hipótese alguma.
neste caso você também não precisa do `if` e você pode usar a constante `LENGTH` para garantir a quantidade de números.

```php
$number = str_pad($this->number, self::LENGTH, 0, STR_PAD_RIGHT);
return preg_replace(self::REGEX, '$1-$2.$3.$4.$5.$6', "{$number}");
```

2018-08-08 03:27 UTC, tonicospinelli commented on src/JudiciaryProcess.php
> +     * Anexo VIII da Resolução CNJ no 65, de 16 de dezembro de 2008.
não conhecia essa validação! obrigado por contribuir!

2018-08-08 12:03 UTC, robmachado commented
Vou providenciar e tem mais uma validação para mandar o dos Processos Administrativos

2018-08-13 13:37 UTC, tonicospinelli requested changes

2018-08-13 13:37 UTC, tonicospinelli commented on src/JudiciaryProcess.php
> +        $number = str_pad($this->number, 20, '0', STR_PAD_RIGHT);
esse `20` é o mesmo que usar o `self::LENGTH`, sugiro que use a constante

2018-08-13 13:37 UTC, tonicospinelli commented on src/JudiciaryProcess.php
> +        return str_pad(substr($number, 0, 7).substr($number, 9, strlen($number)-1), 20, '0', STR_PAD_RIGHT);
- para facilitar a leitura desse método, melhor que separe as linhas do `substr` do `str_pad`
- esse `20` é o mesmo que usar o `self::LENGTH`, sugiro que use a constante

2018-08-15 14:08 UTC, merged